[package]
name = "video-player-rust"
version = "0.1.0"
authors = ["dudko"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ffmpeg-next = "4.3.7"
sdl2 = "0.34"
soundio = "0.2.1"
